### PR TITLE
Wrap `PayForMessage`s in order to remove `WirePayForMessage` from the mempool

### PR DESCRIPTION
**Pull request by evan-forbes**
## Description

This is the second part of [#581](https://github.com/celestiaorg/celestia-core/issues/581) and is blocked by [#582](https://github.com/celestiaorg/celestia-core/pull/582). Please reference those for the problem statement and further details.

part of [#581](https://github.com/celestiaorg/celestia-core/issues/581)
blocked by [#582](https://github.com/celestiaorg/celestia-core/pull/582)

### CODE REVIEW

**Review by liamsi — DISMISSED** [review]
ship it

**Comment by evan-forbes** [comment]
will fix the ci failures soon

**Review by adlerjohn — COMMENTED** [review]
Looks ok, but will wait for CI fixes.

**Review by adlerjohn — DISMISSED** [review]
utACK

**Review by adlerjohn — APPROVED** [review]
utACK 2

**Pull request merged**
